name: scrapy
description: A dart port of the idiomatic python library Scrapy, which provides a fast high-level web crawling & scraping framework for dart and Flutter. 
version: 0.0.3
author: Sacha Arbonel <sacha.arbonel@hotmail.fr>
homepage: https://github.com/Sach97/scrapy.dart
environment:
 sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  
  
  # Check out https://docs.codemagic.io/getting-started/yaml/ for more information

workflows:
    flutter-widget:
        name: Flutter Widget
        environment:
            flutter: dev
        scripts:
            - flutter packages pub get
            - flutter test
